#!/usr/bin/env bash
# Bash script that displays a list of currently running processes.
# a : Select all processes
# u : Select all processes on a terminal, including those of other users
# x : Select processes without controlling ttys

ps -auxf
