#!/usr/bin/env bash
# Bash script that prints out certain strings when a specfic signal is encountered.

sudo touch /var/run/holbertonscript.pid
sudo chmod 777 /var/run/holbertonscript.pid
PID=$$
echo $PID > /var/run/holbertonscript.pid
trap "echo I hate the kill command && rm /var/run/holbertonscript.pid && exit" SIGTERM
trap "rm /var/run/holbertonscript.pid && exit" SIGQUIT
trap "echo Y U no love me?!" SIGINT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
