#!/usr/bin/env bash
# This script is displaying "Holberton School" except the 9th time
i="0"

while [ $i -lt 10 ]
do
    echo "Holberton School"
    i=$((i+1))
    if [ $i = 9 ]
    then
	echo "Hi"
    fi
done
