#!/usr/bin/env bash
# Run Nginx as Nginx
pkill apache2
chmod -R 777 /etc/nginx/
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
service nginx restart

