#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private key ~/.ssh/holberton with the user ubuntu.
chmod 600 ~/.ssh/holberton
ssh -i ~/.ssh/holberton ubuntu@34.73.32.179
